### ISSUE TITLE
Authentication thorough Amazon Cognito

### ISSUE THREAD

**Issue by msolefonte** [jolzee/chat-teneo-vue#4]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
I have seen that Firebase Authentication is possible, or, at least, mentioned, and I would like to know if Cognito Authentication is something you have in mind. I have never used any of them, but currently I need to make use of the Cognito solution.

If it is not that hard, I could do it myself and send you a PR. I would like to help as much as possible.

**Comment by jolzee** [comment]
Yes am aware of Amazon Cognito. It would be great to have that as a configurable alternative. Just tackled Firebase as it was recently needed for a project I was working on. PR would be welcomed

**Comment by msolefonte** [comment]
Hello,

Before moving to Amazon Cognito, I want to understand how Firebase works and it is not good enough explained in the docs. As I get, if I set the Firebase Auth values in `.env`, it just should work, but I can still use the bot without having to register nor login. Shouldn't the bot be disabled until you login? That is what I want.

Thank you. I know that I am asking too much these days.

**Comment by msolefonte** [comment]
Excuse me. Can you help me with this topic? I still have not found how to invoke the Login window without using the side panel.

Thank you.

**Comment by jolzee** [comment]
This is intentional. Many times a virtual assistant can respond to many questions that don't need authentication. When a user asks a question that Teneo deems needs an authenticated user then it can respond to the user suggesting that they authenticate. The user authenticates, a flag is sent to Teneo to let teneo know who is authenticated and then then the user can ask the question again.  

At the moment Leopard sends the user's name and email address but this should be improved in a production system. You might want to send an auth token and have that validated server side. Also you might want to then retrieve information for that user from another source and use that to apply any authorization to specific dialogs. 

These concepts might not translate over to DialogFlow.

The login and register views are defined as routes in `router.js`  which means in a `*.vue` file you can call  `this.$router.push({ name: "login" });`  or `this.$router.push("/login");`

**Comment by msolefonte** [comment]
Thank you. I did my best to integrate it with Cognito and, with few errors, it works. Not production-ready, but I want it for a personal project, so it is ok. Once it is ended, and as much as I can, I would like to send you the PRs as thanks.

**Comment by jolzee** [comment]
Nice work
