### ISSUE TITLE
Problem with embedded chat on mobile

### ISSUE THREAD

**Issue by manugarciac** [jolzee/chat-teneo-vue#5]
**Describe the bug**
I'm testing the embedded chat on a smartphone, but the floating button is not being shown.

**To Reproduce**
1. I changed the `tieUrl` value on `embed-leopard.js` to my URL: `http://192.168.200.249:8080/`
2. I Ran `npm run build`
3. I exposed the dist folder on port 8080.
4. I access `http://192.168.200.249:8080/embed.html`

**Expected behavior**
A floating button should show as in desktop. It would be ideal to then have the chat cover the whole page when clicking on the button.

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S10+
 - OS: Android 9
 - Browser: Chrome
 - Version: 74.0.3729.157

**Additional context**
If I check "Desktop Site" on Chrome, the floating button is shown, so that discards any networking issues. Is this expected behavior for the embedded chat on mobile?

**Comment by jolzee** [comment]
Yes the is the expected behavior. The current configuration is to have Leopard automatically open and full screen when shown in a browser window narrower than 480px. This was done because I use Leopard to demo Teneo regularly to prospects and it helps with displaying it on mobile devices and in the `mobile.html` view that can be accessed from the configuration area of a solution.  The logic aso automatically hides the chat button when in fullscreen mode. You right though it might make more sense to temporarily swap out the dark/light mode button with maybe a close button when shown in the full screen mode. That button will reappear when you resize the the width of the window to be greater than 480px. 

The logic for auto open and the swapping of the buttons could probably be added as a configuration option in the configuration area of each solution. That way it could be suppressed if needed on a solution by solution basis. 

In App.vue check out `mounted()` in there is the logic for automatically opening Leopard based off the widow's width.

Also there's some conditional CSS at the bottom of App.vue that hides the chat button `#chat-open-close-button`  based off the screens max width.
